using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MauiTestApp
{
    internal static class RandomCity
    {
        private static Random _random = new Random();

        public static readonly List<string> _randomCitiesList = new List<string>
        {
            "Tokyo",
            "Delhi",
            "Shanghai",
            "São Paulo",
            "Mexico City",
            "Cairo",
            "Mumbai",
            "Beijing",
            "Dhaka",
            "Osaka",
            "New York",
            "Karachi",
            "Chongqing",
            "Istanbul",
            "Buenos Aires",
            "Kolkata",
            "Kinshasa",
            "Rio de Janeiro",
            "Tianjin",
            "Guangzhou",
            "Lagos",
            "Chengdu",
            "Los Angeles",
            "Moscow",
            "Shenzhen",
            "Lahore",
            "Bangalore",
            "Paris",
            "Bogotá",
            "Johannesburg",
            "Chennai",
            "Lima",
            "Bangkok",
            "Nairobi",
            "Hyderabad",
            "Wuhan",
            "Hangzhou",
            "Ahmedabad",
            "Riyadh",
            "Hanoi",
            "Washington, D.C.",
            "Santiago",
            "Alexandria",
            "Madrid",
            "Barcelona",
            "Detroit",
            "San Francisco",
            "Guadalajara",
            "Montreal",
            "Toronto",
            "Calgary",
            "Vancouver",
            "Bamako",
            "Kuala Lumpur",
            "Vienna",
            "Brisbane",
            "Portland",
            "Atlanta",
            "Dallas",
            "Seattle",
            "Fort Worth",
            "Phoenix",
            "San Diego",
            "Minneapolis",
            "Philadelphia",
            "Houston",
            "Baltimore",
            "Singapore",
            "Kuwait City",
            "Taipei",
            "Amsterdam",
            "Lisbon",
            "Zurich",
            "Geneva",
            "Stockholm",
            "Copenhagen",
            "Oslo",
            "Helsinki",
            "Reykjavik",
            "Düsseldorf",
            "Frankfurt",
            "Munich",
            "Berlin",
            "Stuttgart",
            "Hamburg",
            "Brussels",
            "Antwerp",
            "Freiburg",
            "Cologne",
            "Bremen",
            "Nuremberg",
            "Mannheim",
            "Bonn",
            "Wroclaw",
            "Warsaw",
            "Kraków",
            "Poznań",
            "Gdańsk",
            "Lviv",
            "Kyiv",
            "Odessa",
            "Chisinau",
            "Moscow",
            "Saint Petersburg",
            "Novosibirsk",
            "Yekaterinburg",
            "Kazan",
            "Nizhny Novgorod",
            "Chelyabinsk",
            "Samara",
            "Vladivostok",
            "Irkutsk",
            "Krasnoyarsk",
            "Ufa",
            "Orenburg",
            "Astrakhan",
            "Tyumen",
            "Yaroslavl",
            "Voronezh",
            "Saratov",
            "Volgograd",
            "Krasnodar",
            "Rostov-on-Don",
            "Kaliningrad",
            "Sochi",
            "Simferopol",
            "Tver",
            "Lipetsk",
            "Oryol",
            "Penza",
            "Syktyvkar",
            "Kirov",
            "Tula",
            "Sofia",
            "Bucharest",
            "Athens",
            "Nicosia",
            "Tbilisi",
            "Yerevan",
            "Baku",
            "Ulaanbaatar",
            "Almaty",
            "Astana",
            "Tashkent",
            "Minsk",
            "Vilnius",
            "Riga",
            "Tallinn",
            "Chisinau",
            "Prague",
            "Bratislava",
            "Budapest",
            "Sarajevo",
            "Zagreb",
            "Ljubljana",
            "Podgorica",
            "Belgrade",
            "Skopje",
            "Tirana",
            "Kosice",
            "Ostrava",
            "Brno",
            "Plzeň",
            "Olomouc",
            "Helsinki",
            "Copenhagen",
            "Oslo",
            "Aarhus",
            "Gothenburg",
            "Malmo",
            "Helsingborg",
            "Groningen",
            "Eindhoven",
            "Utrecht",
            "Rotterdam",
            "Amsterdam",
            "The Hague",
            "Antwerp",
            "Ghent",
            "Brugge",
            "Oostende",
            "Malmo",
            "Gothenburg",
            "Stavanger",
            "Bergen",
            "Oslo",
            "Aarhus",
            "Herning",
            "Randers",
            "Alborg",
            "Kolding",
            "Esbjerg",
            "Odense",
            "Sonderborg",
            "Vejle",
            "Aarhus",
            "Kolding",
            "Horsens",
            "Randers",
            "Struer",
            "Dumfries",
            "Inverness",
            "Falkirk",
            "Perth",
            "Stirling",
            "Edinburgh",
            "Glasgow",
            "Aberdeen",
            "Dundee",
            "Wolverhampton",
            "Birmingham",
            "Manchester",
            "Leeds",
            "Sheffield",
            "Liverpool",
            "Bristol",
            "Cardiff",
            "Coventry",
            "Newcastle",
            "Sunderland",
            "Nottingham",
            "Southampton",
            "Brighton",
            "Dover",
            "Exeter",
            "Gloucester",
            "Swindon",
            "Plymouth",
            "Portsmouth",
            "Cheltenham",
            "Luton",
            "St Albans",
            "Milton Keynes",
            "Basildon",
            "Woking",
            "Basingstoke",
            "Slough",
            "Reading",
            "High Wycombe",
            "Burton upon Trent",
            "Leicester",
            "Bradford",
            "Luton",
            "Swindon",
            "Derby",
            "Milton Keynes",
            "Peterborough",
            "Newcastle",
            "Bristol",
            "Coventry",
            "Oxford",
            "London",
            "Brentford",
            "Richmond upon Thames",
            "Sligo",
            "Waterford",
            "Limerick",
            "Galway",
            "Cork",
            "Derry",
            "Belfast",
            "Dun Laoghaire",
            "Swords",
            "Killarney",
            "Kilkenny",
            "Tralee",
            "Wexford",
            "Ennis",
            "Athlone",
            "Letterkenny",
            "Clonmel",
            "Drogheda",
            "Carlow",
            "Naas",
            "Comber",
            "Strabane",
            "Newtownabbey"
        };

        public static string PickRandomCity()
        {
            string randomCityName = _randomCitiesList[_random.Next(_randomCitiesList.Count)];

            return randomCityName;
        }
    }
}
